<?php
$settings = [
    'title' => 'Основные настройки',
    'enable_change' => true,
    'wide_mode' => true,
    'block_enabled' => [
        'my_accordion',
        'my_advantages',
        'my_advantages_type2',
        'my_applicationation',
        'my_applicationation_type2',
        'my_color',
        'my_equipment',
        'my_features',
        'my_files_content',
        'my_form',
        'my_form_simple',
        'my_gallery',
        'my_map',
        'my_news',
        'my_number',
        'my_order',
        'my_order_tabs',
        'my_order_content',
        'my_project',
        'my_render',
        'my_render_select',
        'my_specifications',
        'my_specifications__tabs',
        'my_specifications_content',
        'my_surface',
        'my_text',
        'my_text_image',
        'my_texture',
        'my_type',
        'my_video_gallery',
        'my_economic_benefit',
        'my_compound_probkoviy_germetik',
        'my_applicationation_type3',
        'my_advantages_type3',
        'my_advantages_type4',
        'my_calculator_link',
        'my_sostav_probkovoy_smesi',
        'my_section_triangle',
        'my_circle_diagram',
        'my_image_left_text',
        'my_years_advantages',
        'my_result_for_12years',
        'my_primery_rabot_do_posle',
        'my_avto_files',
        'my_surface_no_slider',
        'my_question_answer_block',
        
     
    ],
    'layout_settings' => [
        'type1' => [],
    ],
    'layout_enabled' => [
        'type1'
    ]
];